services:
  qa-javascript:
    build:
      context: .
    environment:
      API_BASE_URL: http://host.docker.internal:8000
      FRONTEND_BASE_URL: http://host.docker.internal:4173
    extra_hosts:
      - 'host.docker.internal:host-gateway'
